spring:
  datasource:
      url: jbc:h2:mem:testdb
      username: root
      password: toor
      driverClassName: org.h2.Driver
  jpa:
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
